INFO - 2023-02-13 12:06:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 12:50:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 12:56:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 12:56:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 12:59:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 13:02:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 13:06:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 13:07:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 14:08:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-02-13 15:57:58 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'authapp' in C:\laragon\www\authapp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\laragon\www\authapp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'authapp', 3306, '', 0)
#1 C:\laragon\www\authapp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\authapp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\authapp\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\authapp\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\authapp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\authapp\app\validation\UserRules.php(12): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\authapp\system\Validation\Validation.php(312): App\Validation\UserRules->validateUser('12345678', 'email, password', Array, NULL, 'password')
#8 C:\laragon\www\authapp\system\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('password', 'password', '12345678', Array, Array)
#9 C:\laragon\www\authapp\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#10 C:\laragon\www\authapp\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#11 C:\laragon\www\authapp\system\CodeIgniter.php(934): App\Controllers\UserController->index()
#12 C:\laragon\www\authapp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#13 C:\laragon\www\authapp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\laragon\www\authapp\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'authapp' in C:\laragon\www\authapp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\laragon\www\authapp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\authapp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\authapp\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\authapp\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\authapp\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\authapp\app\validation\UserRules.php(12): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\authapp\system\Validation\Validation.php(312): App\Validation\UserRules->validateUser('12345678', 'email, password', Array, NULL, 'password')
#7 C:\laragon\www\authapp\system\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('password', 'password', '12345678', Array, Array)
#8 C:\laragon\www\authapp\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#9 C:\laragon\www\authapp\app\Controllers\UserController.php(27): CodeIgniter\Controller->validate(Array, Array)
#10 C:\laragon\www\authapp\system\CodeIgniter.php(934): App\Controllers\UserController->index()
#11 C:\laragon\www\authapp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#12 C:\laragon\www\authapp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\laragon\www\authapp\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2023-02-13 15:57:58 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'authapp'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\validation\UserRules.php(12): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\Validation\Validation.php(312): App\Validation\UserRules->validateUser('12345678', 'email, password', [...], null, 'password')
 7 SYSTEMPATH\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('password', 'password', '12345678', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\UserController.php(27): CodeIgniter\Controller->validate([...], [...])
10 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserController->index()
11 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
12 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-02-13 20:50:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 20:50:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-02-13 20:51:13 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'authapp' in C:\laragon\www\authapp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\laragon\www\authapp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'authapp', 3306, '', 0)
#1 C:\laragon\www\authapp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\authapp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\authapp\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\laragon\www\authapp\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\authapp\system\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfunded...', 'email', Array, NULL, 'email')
#6 C:\laragon\www\authapp\system\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfunded...', Array, Array)
#7 C:\laragon\www\authapp\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\laragon\www\authapp\app\Controllers\UserController.php(60): CodeIgniter\Controller->validate(Array)
#9 C:\laragon\www\authapp\system\CodeIgniter.php(934): App\Controllers\UserController->register()
#10 C:\laragon\www\authapp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#11 C:\laragon\www\authapp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\authapp\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'authapp' in C:\laragon\www\authapp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\laragon\www\authapp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\authapp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\authapp\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\laragon\www\authapp\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\authapp\system\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfunded...', 'email', Array, NULL, 'email')
#5 C:\laragon\www\authapp\system\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfunded...', Array, Array)
#6 C:\laragon\www\authapp\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#7 C:\laragon\www\authapp\app\Controllers\UserController.php(60): CodeIgniter\Controller->validate(Array)
#8 C:\laragon\www\authapp\system\CodeIgniter.php(934): App\Controllers\UserController->register()
#9 C:\laragon\www\authapp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#10 C:\laragon\www\authapp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\authapp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-02-13 20:51:13 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'authapp'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfundedafrica.com', 'email', [...], null, 'email')
 5 SYSTEMPATH\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfundedafrica.com', [...], [...])
 6 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\UserController.php(60): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserController->register()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-13 20:53:13 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'authapp' in C:\laragon\www\authapp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\laragon\www\authapp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'authapp', 3306, '', 0)
#1 C:\laragon\www\authapp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\authapp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\authapp\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\laragon\www\authapp\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\authapp\system\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfunded...', 'email', Array, NULL, 'email')
#6 C:\laragon\www\authapp\system\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfunded...', Array, Array)
#7 C:\laragon\www\authapp\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\laragon\www\authapp\app\Controllers\UserController.php(60): CodeIgniter\Controller->validate(Array)
#9 C:\laragon\www\authapp\system\CodeIgniter.php(934): App\Controllers\UserController->register()
#10 C:\laragon\www\authapp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#11 C:\laragon\www\authapp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\authapp\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'authapp' in C:\laragon\www\authapp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\laragon\www\authapp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\authapp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\authapp\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\laragon\www\authapp\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\authapp\system\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfunded...', 'email', Array, NULL, 'email')
#5 C:\laragon\www\authapp\system\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfunded...', Array, Array)
#6 C:\laragon\www\authapp\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#7 C:\laragon\www\authapp\app\Controllers\UserController.php(60): CodeIgniter\Controller->validate(Array)
#8 C:\laragon\www\authapp\system\CodeIgniter.php(934): App\Controllers\UserController->register()
#9 C:\laragon\www\authapp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#10 C:\laragon\www\authapp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\authapp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-02-13 20:53:13 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'authapp'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfundedafrica.com', 'email', [...], null, 'email')
 5 SYSTEMPATH\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfundedafrica.com', [...], [...])
 6 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\UserController.php(60): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserController->register()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-13 20:53:27 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'authapp' in C:\laragon\www\authapp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\laragon\www\authapp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'authapp', 3306, '', 0)
#1 C:\laragon\www\authapp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\authapp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\authapp\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\laragon\www\authapp\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\authapp\system\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfunded...', 'email', Array, NULL, 'email')
#6 C:\laragon\www\authapp\system\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfunded...', Array, Array)
#7 C:\laragon\www\authapp\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\laragon\www\authapp\app\Controllers\UserController.php(60): CodeIgniter\Controller->validate(Array)
#9 C:\laragon\www\authapp\system\CodeIgniter.php(934): App\Controllers\UserController->register()
#10 C:\laragon\www\authapp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#11 C:\laragon\www\authapp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\authapp\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'authapp' in C:\laragon\www\authapp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\laragon\www\authapp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\authapp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\authapp\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\laragon\www\authapp\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\authapp\system\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfunded...', 'email', Array, NULL, 'email')
#5 C:\laragon\www\authapp\system\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfunded...', Array, Array)
#6 C:\laragon\www\authapp\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#7 C:\laragon\www\authapp\app\Controllers\UserController.php(60): CodeIgniter\Controller->validate(Array)
#8 C:\laragon\www\authapp\system\CodeIgniter.php(934): App\Controllers\UserController->register()
#9 C:\laragon\www\authapp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#10 C:\laragon\www\authapp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\authapp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-02-13 20:53:27 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'authapp'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfundedafrica.com', 'email', [...], null, 'email')
 5 SYSTEMPATH\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfundedafrica.com', [...], [...])
 6 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\UserController.php(60): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserController->register()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-02-13 20:53:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 20:53:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 20:53:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-02-13 20:53:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-02-13 20:54:17 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'authapp' in C:\laragon\www\authapp\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\laragon\www\authapp\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'authapp', 3306, '', 0)
#1 C:\laragon\www\authapp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\authapp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\authapp\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\laragon\www\authapp\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\authapp\system\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfunded...', 'email', Array, NULL, 'email')
#6 C:\laragon\www\authapp\system\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfunded...', Array, Array)
#7 C:\laragon\www\authapp\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\laragon\www\authapp\app\Controllers\UserController.php(60): CodeIgniter\Controller->validate(Array)
#9 C:\laragon\www\authapp\system\CodeIgniter.php(934): App\Controllers\UserController->register()
#10 C:\laragon\www\authapp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#11 C:\laragon\www\authapp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\authapp\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'authapp' in C:\laragon\www\authapp\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\laragon\www\authapp\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\authapp\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\authapp\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#3 C:\laragon\www\authapp\system\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\authapp\system\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfunded...', 'email', Array, NULL, 'email')
#5 C:\laragon\www\authapp\system\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfunded...', Array, Array)
#6 C:\laragon\www\authapp\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#7 C:\laragon\www\authapp\app\Controllers\UserController.php(60): CodeIgniter\Controller->validate(Array)
#8 C:\laragon\www\authapp\system\CodeIgniter.php(934): App\Controllers\UserController->register()
#9 C:\laragon\www\authapp\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
#10 C:\laragon\www\authapp\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\authapp\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-02-13 20:54:17 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'authapp'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT 1
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Validation\StrictRules\Rules.php(206): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\Validation\Validation.php(312): CodeIgniter\Validation\StrictRules\Rules->is_unique('david@getfundedafrica.com', 'email', [...], null, 'email')
 5 SYSTEMPATH\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('email', 'email', 'david@getfundedafrica.com', [...], [...])
 6 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 7 APPPATH\Controllers\UserController.php(60): CodeIgniter\Controller->validate([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\UserController->register()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UserController))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
